/**
 * 国家名称映射工具
 * 将国家名称转换为 ISO 3166-1 alpha-3 代码（用于地图数据匹配）
 */

/**
 * 国家名称到 ISO 3166-1 alpha-3 代码的映射
 * 支持常见的中英文国家名称
 */
export const countryToISO: Record<string, string> = {
  // 主要国家 - 英文
  'United States': 'USA',
  'United States of America': 'USA',
  'US': 'USA',
  'USA': 'USA',
  'China': 'CHN',
  'People\'s Republic of China': 'CHN',
  'PRC': 'CHN',
  'CN': 'CHN',
  'United Kingdom': 'GBR',
  'UK': 'GBR',
  'GB': 'GBR',
  'Great Britain': 'GBR',
  'Germany': 'DEU',
  'DE': 'DEU',
  'France': 'FRA',
  'FR': 'FRA',
  'Japan': 'JPN',
  'JP': 'JPN',
  'Canada': 'CAN',
  'CA': 'CAN',
  'Italy': 'ITA',
  'IT': 'ITA',
  'Spain': 'ESP',
  'ES': 'ESP',
  'India': 'IND',
  'IN': 'IND',
  'Australia': 'AUS',
  'AU': 'AUS',
  'South Korea': 'KOR',
  'Korea': 'KOR',
  'KR': 'KOR',
  'Netherlands': 'NLD',
  'NL': 'NLD',
  'Switzerland': 'CHE',
  'CH': 'CHE',
  'Sweden': 'SWE',
  'SE': 'SWE',
  'Singapore': 'SGP',
  'SG': 'SGP',
  'Israel': 'ISR',
  'IL': 'ISR',
  'Brazil': 'BRA',
  'BR': 'BRA',
  'Russia': 'RUS',
  'Russian Federation': 'RUS',
  'RU': 'RUS',
  'Belgium': 'BEL',
  'BE': 'BEL',
  'Austria': 'AUT',
  'AT': 'AUT',
  'Denmark': 'DNK',
  'DK': 'DNK',
  'Finland': 'FIN',
  'FI': 'FIN',
  'Norway': 'NOR',
  'NO': 'NOR',
  'Poland': 'POL',
  'PL': 'POL',
  'Taiwan': 'TWN',
  'TW': 'TWN',
  'Hong Kong': 'HKG',
  'Hong Kong SAR': 'HKG',
  'HK': 'HKG',
  'Ireland': 'IRL',
  'IE': 'IRL',
  'New Zealand': 'NZL',
  'NZ': 'NZL',
  'Portugal': 'PRT',
  'PT': 'PRT',
  'Greece': 'GRC',
  'GR': 'GRC',
  'Czech Republic': 'CZE',
  'CZ': 'CZE',
  'Turkey': 'TUR',
  'TR': 'TUR',
  'Mexico': 'MEX',
  'MX': 'MEX',
  'Chile': 'CHL',
  'CL': 'CHL',
  'Argentina': 'ARG',
  'AR': 'ARG',
  'South Africa': 'ZAF',
  'ZA': 'ZAF',
  'Egypt': 'EGY',
  'EG': 'EGY',
  'Thailand': 'THA',
  'TH': 'THA',
  'Malaysia': 'MYS',
  'MY': 'MYS',
  'Indonesia': 'IDN',
  'ID': 'IDN',
  'Philippines': 'PHL',
  'PH': 'PHL',
  'Vietnam': 'VNM',
  'VN': 'VNM',
  'Saudi Arabia': 'SAU',
  'SA': 'SAU',
  'United Arab Emirates': 'ARE',
  'UAE': 'ARE',
  'AE': 'ARE',
  'Unknown': '',
};

/**
 * 将国家名称转换为 ISO 3166-1 alpha-3 代码
 */
export function getCountryISO(countryName: string): string {
  if (!countryName) return '';
  
  const normalized = countryName.trim();
  return countryToISO[normalized] || countryToISO[normalized.toUpperCase()] || '';
}

/**
 * ISO 代码到国家名称的映射（用于显示）
 */
export const isoToCountryName: Record<string, string> = {
  'USA': 'United States',
  'CHN': 'China',
  'GBR': 'United Kingdom',
  'DEU': 'Germany',
  'FRA': 'France',
  'JPN': 'Japan',
  'CAN': 'Canada',
  'ITA': 'Italy',
  'ESP': 'Spain',
  'IND': 'India',
  'AUS': 'Australia',
  'KOR': 'South Korea',
  'NLD': 'Netherlands',
  'CHE': 'Switzerland',
  'SWE': 'Sweden',
  'SGP': 'Singapore',
  'ISR': 'Israel',
  'BRA': 'Brazil',
  'RUS': 'Russia',
  'BEL': 'Belgium',
  'AUT': 'Austria',
  'DNK': 'Denmark',
  'FIN': 'Finland',
  'NOR': 'Norway',
  'POL': 'Poland',
  'TWN': 'Taiwan',
  'HKG': 'Hong Kong',
  'IRL': 'Ireland',
  'NZL': 'New Zealand',
  'PRT': 'Portugal',
  'GRC': 'Greece',
  'CZE': 'Czech Republic',
  'TUR': 'Turkey',
  'MEX': 'Mexico',
  'CHL': 'Chile',
  'ARG': 'Argentina',
  'ZAF': 'South Africa',
  'EGY': 'Egypt',
  'THA': 'Thailand',
  'MYS': 'Malaysia',
  'IDN': 'Indonesia',
  'PHL': 'Philippines',
  'VNM': 'Vietnam',
  'SAU': 'Saudi Arabia',
  'ARE': 'United Arab Emirates',
};
